# Generated by Django 4.2.15 on 2024-09-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ULogin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes'),
        ),
        migrations.AddField(
            model_name='user',
            name='secret_2fa',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='status_2fa',
            field=models.BooleanField(default=False),
        ),
    ]
