# Generated by Django 4.2.15 on 2024-09-06 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ULogin', '0002_user_qr_image_user_secret_2fa_user_status_2fa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='qr_image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='secret_2fa',
        ),
        migrations.RemoveField(
            model_name='user',
            name='status_2fa',
        ),
    ]
