# Generated by Django 4.2.15 on 2024-09-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ULogin', '0008_alter_user_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img_url',
            field=models.ImageField(default='profile_pics/1177568.png', upload_to='profile_pics'),
        ),
    ]
