# Generated by Django 4.2.15 on 2024-10-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ULogin', '0015_remove_user_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
