# Generated by Django 4.2.15 on 2024-10-07 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ULogin', '0018_user_is_online'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockFriend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_friends', models.ManyToManyField(blank=True, related_name='block_friends_of', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='block_friend_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
