# Generated by Django 5.1 on 2024-11-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='reject_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
