# Generated by Django 5.1 on 2024-11-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_reject_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='fulfill_label',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='reject_label',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
