# Generated by Django 4.2.16 on 2024-09-26 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='tournament.player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='tournament.player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner', to='tournament.player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this player belongs to.', related_name='player_user_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='player',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this player.', related_name='player_user_permissions_set', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='room',
            name='players',
            field=models.ManyToManyField(to='tournament.player'),
        ),
    ]
