# Generated by Django 4.2.15 on 2024-10-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_alter_match_id_alter_room_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='score1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='score2',
            field=models.IntegerField(default=0),
        ),
    ]
