# Generated by Django 5.1 on 2024-11-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fulfill_link', models.CharField(blank=True, max_length=255, null=True)),
                ('reject_link', models.BooleanField(default=False)),
                ('fulfill_label', models.CharField(max_length=20)),
                ('reject_label', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
