# Generated by Django 5.1 on 2024-11-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_invite',
            field=models.BooleanField(default=False),
        ),
    ]
