# Generated by Django 5.1 on 2024-11-01 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchGame',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('player1_score', models.IntegerField(default=0)),
                ('player2_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('is_invite_only', models.BooleanField(default=False)),
            ],
        ),
    ]
