# Generated by Django 4.2.15 on 2024-10-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_matchgame_player1_remove_matchgame_player2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchgame',
            name='is_invite_only',
            field=models.BooleanField(default=False),
        ),
    ]
