# Generated by Django 4.2.15 on 2024-09-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ULogin', '0002_alter_user_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
