# Generated by Django 4.2.15 on 2024-09-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ULogin', '0004_user_state_2fa_alter_user_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img_qr',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes'),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
