# Generated by Django 4.2.15 on 2024-09-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ULogin', '0005_user_img_qr_user_otp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='totp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
