# Generated by Django 4.2.15 on 2024-09-11 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ULogin', '0006_user_totp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='totp',
        ),
    ]
